version: '2'
services:
  back:
    build: ./back/pimp-my-trad-api
    ports:
      - 8080
    environment:
      - MONGO_HOST=mongo
      - DATA_ROOT=/opt/pmtdata
      - SPRING_PROFILE=docker
    depends_on:
      - mongo
    volumes:
      - pmt-data:/opt/pmtdata
  front:
    build: ./front
    ports:
      - 80:80
    environment:
      - PMT_API=back
      - PMT_PORT=8080
  mongo:
    image: library/mongo:3.2
    volumes:
      - db-data:/data/db
volumes:
  db-data:
  pmt-data: